name: khub_mobile
description: "Informing health decisions and action in Africa"
publish_to: 'none'

version: 1.0.7+9

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  loading_animation_widget: ^1.3.0
  http: ^1.4.0
  flutter_dotenv: ^5.2.1
  carousel_slider: ^5.1.1
  dio: ^5.8.0+1
  retrofit: ^4.5.0
  logger: ^2.6.0
  json_annotation: ^4.9.0
  go_router: ^15.1.2
  shared_preferences: ^2.5.3
  path: ^1.9.0
  provider: ^6.1.5
  url_launcher: ^6.3.1
  get_it: ^8.0.3
  flutter_local_notifications: ^19.3.0
  flutter_native_splash: ^2.4.4
  cached_network_image: ^3.4.1
  permission_handler: ^12.0.1
  clipboard: ^0.1.3
  font_awesome_flutter: ^10.8.0
  timeago: ^3.7.1
  flutter_html: ^3.0.0-beta.2
  html: ^0.15.4
  pretty_dio_logger: ^1.4.0
  awesome_dialog: ^3.2.1
  sqflite: ^2.4.1
  http_parser: ^4.0.2
#  syncfusion_flutter_pdfviewer: ^28.2.5
  webview_flutter: ^4.10.0
  rxdart: ^0.28.0
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  device_info_plus: ^11.3.0
  quill_html_editor:
    path: ./quill_html_editor
  share_plus: ^11.0.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  google_sign_in: ^6.2.2
  firebase_auth: ^5.3.2
  aad_oauth: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.5
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/launcher.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true  # This enables the generation of localizations

  assets:
    - assets/africa_cdc.jpg
    - assets/images/default_user.jpg
    - assets/images/placeholder.jpg
    - assets/data/publications.json
    - assets/data/recent_publications.json
    - assets/data/themes.json
    - assets/data/forums.json
    - assets/data/notifications.json
    - assets/images/google_icon.png
    - assets/images/microsoft_icon.png
    - .env

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu-Light.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
        - asset: assets/fonts/Ubuntu-RegularItalic.ttf

flutter_native_splash:
  color: "#ffffff"
  image: assets/africa_cdc.jpg
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
