name: khub_mobile
description: "Informing health decisions and action in Africa"
publish_to: 'none'

version: 1.0.5+7

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0  # Already present in your dependencies
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  loading_animation_widget: ^1.2.1
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  carousel_slider: ^5.0.0
  video_player: ^2.9.0
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  logger: ^2.3.0
  built_value: ^8.9.2
  json_annotation: ^4.9.0
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  path: ^1.9.0
  provider: ^6.1.2
  url_launcher: ^6.3.1
  get_it: ^8.0.2
  flutter_local_notifications: ^18.0.0
  flutter_native_splash: ^2.4.0
  cached_network_image: ^3.3.1
  permission_handler: ^11.3.1
  clipboard: ^0.1.3
  font_awesome_flutter: ^10.7.0
  timeago: ^3.6.1
  flutter_html: ^3.0.0-beta.2
  html: ^0.15.4
  pretty_dio_logger: ^1.4.0
  awesome_dialog: ^3.2.1
  another_flushbar: ^1.12.30
  sqflite: ^2.3.3+1
  http_parser: ^4.0.2
  syncfusion_flutter_pdfviewer: ^26.2.10
  path_provider: ^2.1.4
  webview_flutter: ^4.8.0
  rxdart: ^0.28.0
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  device_info_plus: ^10.1.2
  quill_html_editor:
    path: ./quill_html_editor
  share_plus: ^10.0.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  google_sign_in: ^6.2.2
  firebase_auth: ^5.3.2
  aad_oauth: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.4
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/launcher.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true  # This enables the generation of localizations

  assets:
    - assets/africa_cdc.jpg
    - assets/images/default_user.jpg
    - assets/images/placeholder.jpg
    - assets/data/publications.json
    - assets/data/recent_publications.json
    - assets/data/themes.json
    - assets/data/forums.json
    - assets/data/notifications.json
    - assets/images/google_icon.png
    - assets/images/microsoft_icon.png
    - .env

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu-Light.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
        - asset: assets/fonts/Ubuntu-RegularItalic.ttf

flutter_native_splash:
  color: "#ffffff"
  image: assets/africa_cdc.jpg
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
